### ISSUE TITLE
Index out of Bounds on Server load - Craft of Exile 2.2.1, Custom Quests 1.0.1

### ISSUE THREAD

**Issue by kirkRudzinski** [vincentmet/CustomQuests#29]
On server load the below error is produced

[RandomPatches ServerTickList Transformer]: Patching method: <init> (<init>)
[20:02:06] [Server thread/INFO] [STDERR/]: [com.vincentmet.customquests.lib.Utils:getNbtFromJson:124]: com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
[20:02:06] [Server thread/INFO] [STDERR/]: [com.vincentmet.customquests.lib.Utils:getNbtFromJson:124]: com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
Index: 2
[20:02:06] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Index: 1, Size: 1
Listeners:
0: NORMAL
1: ASM: class com.dynamic_view.event.EventHandler onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
2: ASM: class com.vincentmet.customquests.lib.handlers.EventHandler onWorldStart(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
3: ASM: class com.ldtteam.structurize.event.EventSubscriber onServerStarting(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
4: ASM: class net.telepathicgrunt.bumblezone.entities.BeeAggressionBehavior$ForgeEvents SetupBeeHatingList(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
7: ASM: class com.simibubi.create.CommonEvents onLoadWorld(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
6: ASM: class com.mushroom.midnight.common.util.SessionLocal onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
5: ASM: com.lycanitesmobs.GameEventListener@5a7cfc2c onWorldLoading(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
8: ASM: class blusunrize.immersiveengineering.common.util.FakePlayerUtil onLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
10: LOWEST
9: ASM: blusunrize.immersiveengineering.common.EventHandler@aa96644 onLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
11: ASM: class com.minecolonies.coremod.event.EventHandler onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at com.vincentmet.customquests.quests.progress.QuestRequirementStatus.<init>(QuestRequirementStatus.java:20)
at com.vincentmet.customquests.lib.handlers.StructureHandler.initSingleQuestingUserProgress(StructureHandler.java:260)
at com.vincentmet.customquests.lib.handlers.StructureHandler.initQuestingProgress(StructureHandler.java:249)
at com.vincentmet.customquests.lib.handlers.StructureHandler.initSingleQuestProgressForUser(StructureHandler.java:278)
at com.vincentmet.customquests.lib.handlers.EventHandler.onWorldStart(EventHandler.java:178)
at net.minecraftforge.eventbus.ASMEventHandler_171_EventHandler_onWorldStart_Load.invoke(.dynamic)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
at com.vincentmet.customquests.lib.handlers.StructureHandler.initSingleQuestingUserProgress(StructureHandler.java:260) ~[?:1.15.2-1.0.1] {re:classloading}
g}
at com.vincentmet.customquests.lib.handlers.StructureHandler.initQuestingProgress(StructureHandler.java:249) ~[?:1.15.2-1.0.1] {re:classloading}
at com.vincentmet.customquests.lib.handlers.EventHandler.onWorldStart(EventHandler.java:178) ~[?:1.15.2-1.0.1] {re:classloading,pl:runtimedistcleaner:A} at net.minecraftforge.eventbus.ASMEventHandler_171_EventHandler_onWorldStart_Load.invoke(.dynamic) ~[?:?] {}(B
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:414) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) ~[?:?] {re:classloading,pl:accesstransformer:B}
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}

I'll be attaching the crash log and quest config files
[crash-2020-08-17_19.59.12-server.txt](https://github.com/vincentmetevelis/CustomQuests/files/5086550/crash-2020-08-17_19.59.12-server.txt)

[CustomQuestsErrorLogs.zip](https://github.com/vincentmetevelis/CustomQuests/files/5086551/CustomQuestsErrorLogs.zip)

**Comment by vincentmetevelis** [comment]
This happens when the mod cant automagically fix the progress file after quests have changed. There are 2 ways to solve this, 1: delete the progress file, 2: manually fix the progress file, (that will need some knowledge of JSON, and how it's saved)

**Comment by kirkRudzinski** [comment]
Lets say that I want to try and fix the progress file, I do know JSON.  Is it just a matter of locating the missing { } or is there something else?

What’s the name/location of the progress file?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vincentmetevelis** [comment]
what it comes down to, is that each subrequirement has its own value, therefor you need to change the arrays to match the amount of requirements and subrequirements. Kinda the same goes for the quest objects

**Comment by vincentmetevelis** [comment]
Closed due to inactivity
